### ISSUE TITLE
Wiring Schema

### ISSUE THREAD

**Issue by JotaStar** [theGanymedes/si4432#1]
Hi,

I bought a couple of this and I'm trying to run your code.

Can you please write the wiring schema with Arduino Pro Mini pins?

Thank you.

**Comment by theGanymedes** [comment]
Sorry, I just saw this :)

Project uses standart SPI header pins for SPI comm. However, you need to use a level shifter (or some equivalent IC or solution) for converting 5V arduino outputs to 3.3V. Used resistor-divider circuit, but this enforces SPI connection to transmit at slower rates.

For SDN and IRQ Pin, you can use any. Construtor takes parameters for these pins anyway. However, don't forget that not all Arduino pins can handle IRQ's. In my case, I used Pin2. Library works without interrupts too, so if you don't pass any pin for IRQ, it automatically uses busy-waits rather than interrupts.

Hope this helps
